In [1]:
import pandas as pd

data = {
    "refund": ["yes", "no", "no", "yes", "no", "no", "yes", "no", "no", "no"],
    "marital": ["single", "married", "single", "married", "divorced",
                "married", "divorced", "single", "married", "single"],
    "tincome": [125000, 100000, 70000, 120000, 95000,
                60000, 220000, 85000, 75000, 90000],
    "cheat": ["no", "no", "no", "no", "yes", "no", "no", "yes", "no", "yes"]
}
df=pd.DataFrame(data)

In [2]:
df.index.name = "tid"
df.index = [1,2,3,4,5,6,7,8,9,10]
df

   refund   marital  tincome cheat
1     yes    single   125000    no
2      no   married   100000    no
3      no    single    70000    no
4     yes   married   120000    no
5      no  divorced    95000   yes
6      no   married    60000    no
7     yes  divorced   220000    no
8      no    single    85000   yes
9      no   married    75000    no
10     no    single    90000   yes

In [3]:
df.iloc[[0,4,7,8]]

  refund   marital  tincome cheat
1    yes    single   125000    no
5     no  divorced    95000   yes
8     no    single    85000   yes
9     no   married    75000    no

In [4]:
df.iloc[2:7]

  refund   marital  tincome cheat
3     no    single    70000    no
4    yes   married   120000    no
5     no  divorced    95000   yes
6     no   married    60000    no
7    yes  divorced   220000    no

In [5]:
df.iloc[3:8,1:4]

    marital  tincome cheat
4   married   120000    no
5  divorced    95000   yes
6   married    60000    no
7  divorced   220000    no
8    single    85000   yes

In [6]:
df.iloc[:,0:3]

   refund   marital  tincome
1     yes    single   125000
2      no   married   100000
3      no    single    70000
4     yes   married   120000
5      no  divorced    95000
6      no   married    60000
7     yes  divorced   220000
8      no    single    85000
9      no   married    75000
10     no    single    90000

In [7]:
from google.colab import files

uploaded = files.upload()
import pandas as pd

df1 = pd.read_csv("Iris.csv")

df1.head()

Saving Iris.csv to Iris.csv

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [8]:
df1

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [9]:
df1 = df1.drop(index=4)
df1 = df1.drop(columns=df1.columns[3])
print(df1)

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

In [10]:
from google.colab import files

uploaded = files.upload()

Saving sample.csv to sample.csv

In [11]:
df2=pd.read_csv("sample.csv")
df2

,Employee_ID,Name,Department,Age,Salary,Yoe,Join-date,Gender,Bonus,Rating
0,101,alice,HR,29,50000,4,15/03/2020,Female,5000,4.5
1,102,bob,IT,34,70000,8,19/07/2017,Male,7000,4.0
2,103,charlie,IT,41,65000,10,01/06/2020,Male,6000,3.8
3,104,diana,Marketing,28,50000,3,10/02/2021,Female,4500,4.7
4,105,edward,Sales,38,60000,12,25/11/2010,Male,5000,3.5

In [12]:
df2.shape

(5, 10)

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  5 non-null      int64
 1   Name         5 non-null      object
 2   Department   5 non-null      object
 3   Age          5 non-null      int64
 4   Salary       5 non-null      int64
 5   Yoe          5 non-null      int64
 6   Join-date    5 non-null      object
 7   Gender       5 non-null      object
 8   Bonus        5 non-null      int64
 9   Rating       5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [14]:
df2.describe()

       Employee_ID        Age       Salary        Yoe   Bonus    Rating
count     5.000000   5.000000      5.00000   5.000000     5.0  5.000000
mean    103.000000  34.000000  59000.00000   7.400000  5500.0  4.100000
std       1.581139   5.612486   8944.27191   3.847077  1000.0  0.494975
min     101.000000  28.000000  50000.00000   3.000000  4500.0  3.500000
25%     102.000000  29.000000  50000.00000   4.000000  5000.0  3.800000
50%     103.000000  34.000000  60000.00000   8.000000  5000.0  4.000000
75%     104.000000  38.000000  65000.00000  10.000000  6000.0  4.500000
max     105.000000  41.000000  70000.00000  12.000000  7000.0  4.700000

In [15]:
df2.head(5)

,Employee_ID,Name,Department,Age,Salary,Yoe,Join-date,Gender,Bonus,Rating
0,101,alice,HR,29,50000,4,15/03/2020,Female,5000,4.5
1,102,bob,IT,34,70000,8,19/07/2017,Male,7000,4.0
2,103,charlie,IT,41,65000,10,01/06/2020,Male,6000,3.8
3,104,diana,Marketing,28,50000,3,10/02/2021,Female,4500,4.7
4,105,edward,Sales,38,60000,12,25/11/2010,Male,5000,3.5

In [16]:
df2.tail(3)

,Employee_ID,Name,Department,Age,Salary,Yoe,Join-date,Gender,Bonus,Rating
2,103,charlie,IT,41,65000,10,01/06/2020,Male,6000,3.8
3,104,diana,Marketing,28,50000,3,10/02/2021,Female,4500,4.7
4,105,edward,Sales,38,60000,12,25/11/2010,Male,5000,3.5

In [17]:
df2["Salary"].mean()

np.float64(59000.0)

In [18]:
df2["Bonus"].sum()

np.int64(27500)

In [19]:
df2["Age"].min()

28

In [20]:
df2["Rating"].max()

4.7

In [24]:
df2.sort_values(by="Salary", ascending=False)

,Employee_ID,Name,Department,Age,Salary,Yoe,Join-date,Gender,Bonus,Rating
1,102,bob,IT,34,70000,8,19/07/2017,Male,7000,4.0
2,103,charlie,IT,41,65000,10,01/06/2020,Male,6000,3.8
4,105,edward,Sales,38,60000,12,25/11/2010,Male,5000,3.5
0,101,alice,HR,29,50000,4,15/03/2020,Female,5000,4.5
3,104,diana,Marketing,28,50000,3,10/02/2021,Female,4500,4.7

In [44]:
def performance(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

df2["Performance"] = df2["Rating"].apply(performance)

print(df2)

   Employee_ID     Name Department  Age  Salary  Yoe   Join-date  Gender  \
0          101    alice         HR   29   50000    4  15/03/2020  Female
1          102      bob         IT   34   70000    8  19/07/2017    Male
2          103  charlie         IT   41   65000   10  01/06/2020    Male
3          104    diana  Marketing   28   50000    3  10/02/2021  Female
4          105   edward      Sales   38   60000   12  25/11/2010    Male

   Bonus  Rating   ID     Tax Performance
0   5000     4.5  101  5000.0   Excellent
1   7000     4.0  102  7000.0        Good
2   6000     3.8  103  6500.0     Average
3   4500     4.7  104  5000.0   Excellent
4   5000     3.5  105  6000.0     Average

In [27]:
df2.isnull()

,Employee_ID,Name,Department,Age,Salary,Yoe,Join-date,Gender,Bonus,Rating
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False

In [32]:
df.rename(columns={"Employee_ID": "ID"}, inplace=True)

In [38]:
df2[df2["Yoe"] > 5]

,Employee_ID,Name,Department,Age,Salary,Yoe,Join-date,Gender,Bonus,Rating,ID
1,102,bob,IT,34,70000,8,19/07/2017,Male,7000,4.0,102
2,103,charlie,IT,41,65000,10,01/06/2020,Male,6000,3.8,103
4,105,edward,Sales,38,60000,12,25/11/2010,Male,5000,3.5,105

In [40]:
df2[df2["Department"] == "IT"]

,Employee_ID,Name,Department,Age,Salary,Yoe,Join-date,Gender,Bonus,Rating,ID
1,102,bob,IT,34,70000,8,19/07/2017,Male,7000,4.0,102
2,103,charlie,IT,41,65000,10,01/06/2020,Male,6000,3.8,103

In [41]:
df2["Tax"] = df2["Salary"] * 0.10

In [42]:
df.to_csv("employees_modified.csv", index=False)